### ISSUE TITLE
Adjust the placeholder text in the field based on the dropdown menu selection

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-barcode-scanner#8]
**Summary**
An event organizer shared that they had some difficulty with barcode scanner.

After a couple of questions, I learned:

- The didn't use a barcode scanner although they have a couple of them
- They tried to manually type in a code and when that didn't work they used the manual check-in screen

Where they appeared to get stuck was searching for attendee names and then typing in a code.

I tried this on my end and I immediately tried to search for a name on the default screen. I then switched the dropdown to lookup attendee and then I was able to find the attendees.

However, I noticed that the placeholder or help text that is in the field is the same for all of the fields.

![image 2018-11-06 at 8 50 30 am](https://user-images.githubusercontent.com/1079138/48133181-f54e7700-e263-11e8-9dc9-0a940d4b5831.png)

Could we adjust it so it says something like the following?

`Enter an attendee's name here.`

**Reported or seen on**
https://secure.helpscout.net/conversation/696044723/580841?folderId=284418

**Comment by sethshoultes** [comment]
I would also recommend changing the title font size to something a bit smaller to accommodate for longer event names. The event title could also use some line-height in case it wraps.

**Comment by nerrad** [comment]
I've already got a good start on the react app that will replace this scanner and it will work much better for this process.  The new react app is a part of [this pull](https://github.com/eventespresso/eea-barcode-scanner/pull/7) and will works with both the existing shortcode and the blocks (since the app itself will also be embedded on the dedicated admin page).

I think the current app is a candidate for replacement because it's more fragile than the new react app will be.

**Comment by sethshoultes** [comment]
Oh okay. Thanks for the heads up. How much time do you estimate until that's ready for testing?

**Comment by nerrad** [comment]
It's currently on hold because of the other GB work I've been doing.  Some of the GB related work that is _done_ was directly prompted by work I was doing on the barcode scanner app.

I honestly can't give you an accurate estimate for time remaining because there's still some unknowns with the app development and I've been away from it for a while so I'm not sure how much remains to be done on it - pretty sure I have all the main components mapped out and I was just in the process of doing the logic in each one.

One reason I picked the Barcode scanner app to work on while Brent was initially working on the EventAttendees shortcode is because I knew it would help me identify various things needing built in the js core framework for use in EE and add-ons.  I think that will still be the case as the app will have writes it needs to do (i.e. for recording check-ins and check-outs) and we don't have write handling in the js framework yet (although a lot of the supporting stuff _is_ ready for it).  The write handling will be needed for the work Brent is doing on REM as well.
